syntax on
map S :w<CR>
map Q :q<CR>
map R :source $MYVIMRC<CR>
set number
set relativenumber
set cursorline
set wrap
set showcmd
set wildmenu
set hlsearch
exec "nohlsearch"
set incsearch
set ignorecase
set smartcase
